server:
  application:
    name: sprint-boot-kotlin--grpc

logging:
  level:
    root: DEBUG

grpc:
  server:
    port: 6789

spring:
  application:
    name: sprint-boot-kotlin--grpc

  flyway:
    enabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: ''
